### ISSUE TITLE
misleading catalog statistics of catalogs overlapping the IDL

### ISSUE THREAD

**Issue by thbeutin** [SCECcode/csep2#20] opened 2020-03-24 14:02 UTC
By loading a semi-artificial catalog overlapping the International Date Line i discovered very misleading stats :

```
$ ipython
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from csep.core.catalogs import JmaCsvCatalog

In [2]: c = JmaCsvCatalog(filename = '../../Documents/JMA/JMA-hypocenter-timestamp-shifted-area-only.csv')

In [3]: c.load_catalog()
Out[3]: <csep.core.catalogs.JmaCsvCatalog at 0x7fd4a61e8cc0>

In [4]: print(c)

        Name: None

        Start Date: 1923-01-08 04:46:29.170000+00:00
        End Date: 2014-05-31 14:58:40.910000+00:00

        Latitude: (17.4093, 52.5082)
        Longitude: (-179.9999, 179.9999)

        Min Mw: -1.6
        Max Mw: 9.0

        Event Count: 2508992
        

In [5]: 
```

![JMA calaog stats shifted, area only](https://user-images.githubusercontent.com/1901339/77433016-1c690280-6ddf-11ea-965f-570dd0381306.png)

Shouldn't the longitude be something like [165 .. 180), [-180 .. -165] instead of (-179.9999, 179.9999)? Or should we report here just the centroid of the epicenter cloud and the maximum distance of the events?

**Comment by thbeutin** [comment] 2020-03-24 14:06
Probably i should replace IDL by "180° line of longitude"...

**Comment by thbeutin** [comment] 2020-03-24 15:10
This is the real Japanes catalog data:

![JMA-hypocenter](https://user-images.githubusercontent.com/1901339/77441560-dbc2b680-6de9-11ea-9186-6bc11c67515a.png)

**Comment by wsavran** [comment] 2020-03-24 17:03
thomas i see your point. right now this method simply just computes min, and max of the catalog values. in this case its working as intended. if you can suggest an alternative solution id be happy to consider.

**Comment by thbeutin** [comment] 2020-03-27 14:56
for the longterm i'd suggest some values like centroid, average event distance from centroid, and/or maximum event distance from centroid.

**Comment by wsavran** [comment] 2020-08-13 18:08
closing now

**Closed by wsavran** 2020-08-13 18:08 UTC
